version: "3.6"

services:
  mailprint:
    container_name: "mailprint"
    image: ghcr.io/kth-biblioteket/kthb-mailprint-docker:main
    env_file:
      - ./.env
    networks:
      - "apps-net"
    restart: "always"
    volumes:
      - "/home/kthb/maildir:/maildir"

networks:
  apps-net:
    external: true